# .pre-commit-config.yaml
default_language_version:
  python: python3.11
default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks  # general checks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=4096']
        exclude: "([a-zA-Z0-9_]{1,}\\.ipynb|.+?\\.png)"
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude : ^.vscode/
      - id: pretty-format-json
        args: ['--autofix']
        exclude : ^.vscode/
      - id: debug-statements
      - id: detect-private-key
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: no-commit-to-branch
      #   args: [--branch, master]
  